## Main configuration

# discord token (https://discord.com/developers/applications)
DISCORD_TOKEN = ""

# gemini api key (https://aistudio.google.com/apikey)
# yes, it is free with some boundaries
GEMINI_API_KEY = ""

# gemini model id (https://ai.google.dev/gemini-api/docs/models/#model-variations)
# GEMINI_MODEL = "gemini-2.5-flash"
GEMINI_MODEL = "gemini-2.5-flash"

# aliases the bot will respond to (exception: the ping and replying)
# ALIASES = [ "dave", "domain" ]
ALIASES = []

# locale of the bot (used for date formatting) https://simplelocalize.io/data/locales/
# this also changes the language of some things, if it got translated
# help us translate: https://crowdin.com/project/domain-unchained
LOCALE = "hu-HU"

# webui port
# you shouldn't allow this port to be accesible from the internet
WEBUI_PORT = 4500

# administrator user ids, capable of running some commands not available for regular users
# this excludes running the /debug command
OWNERS = []

# searx base url, used every time the bot needs to search something
# SEARX_BASE_URL = "http://search.local"
SEARX_BASE_URL = ""

# total number of messages to be stored in the history
# if it would exceed, the history rollovers
MAX_MESSAGES = 200

# sleeping range for the bot, during this time it will not respond to anything except slash commands
# SLEEPINGRANGE = "22:30-6:00"
SLEEPINGRANGE = ""

# proxies to be used for requests
# PROXIES = [
#   {
#       protocol = "http",
#       host = "proxy.local",
#       port = 8080,
#       auth = {
#           username = "proxyuser",
#           password = "proxypass"
#       }
#   }
# ]
PROXIES = []

# remote blocklists (hosts), must be an url to the plaintext file
REMOTE_LISTS = []

# enables the thinking capabilities of the model (if it supports it)
ENABLE_THINKING = true
# let's the bot think more about the question (bumps the 8000 thinking budget to 20000)
DEEPER_THINKING = true

# the gemini api key for Contextual Responding, useful if your bot gets a lot of messages
# you may use a different account's key here
# we don't recommend using different accounts, as it may lead to issues with the tos
CR_GEMINI_API_KEY = ""

# set to false, so it doesn't "bootloop"
NEEDS_SETUP = true

# cumulative mode
# classic, noise, worse
CUMULATIVE_MODE = "classic"

# tos url
# example: https://anchietae.cc/docs/domain-tos
TOS_URL = ""

# mute count before the user gets automatically banned from using the bot
# this excludes using slash commands
BAN_AFTER = 20

# the default prompt that will be used when using the /call command
DEFAULT_PROMPT = "default.md"

# this allows the bot to use a boxie environment with it's terminal tool
# we don't recommend using this as it is not very useful/secure
# i mean if you run the bot in a different, seperated and isolated virtual machine/environment, then it is fine
ALLOW_SANDBOX = false

# channels to be tracked
[CHANNELS]
# prompt: prompt file to be used
# wikis: list of wiki urls to be used in the channel, can be useful for context
# contextRespond: if true, the bot will use a context-aware response system

# "12312312324312123" = { prompt = "default.md", wikis = [], contextRespond = false }

# timings, should be in milliseconds
# these are all undocumented for a reason
[TIMINGS]
# these values should be left as they are
# and should not be changed
resetPrompt = 600
userCacheDuration = 3600000

# emojis, these should be uploaded to a server where the bot is present / on discord's developer portal
[EMOJIS]
# upload indicators
uploaded = ""
uploading = ""
# releated to reputation
upvote = ""
downvote = ""
# miscellaneous
search = ""
mute = ""